version: "3"
services:
  db:
    image: mysql:5.7.25
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./tertiary.sql:/docker-entrypoint-initdb.d/tertiary.sql
  web:
    build: .
    container_name: "app_web"
    command: bash -c "yarn install --check-files && /bin/bash"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    restart: always
    ports:
      - 8282:80