default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: db
  username: root
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: app_primary_development
  secondary:
    <<: *default
    database: app_secondary_development
    migrations_paths: "db/secondary_migrate"
  tertiary:
    <<: *default
    database: app_tertiary_development
    replica: true